require('packer-config')
require('colorschemes')
require('nvim-tree-config')
require('bufferline-config')
require('alpha-config')
require('telescope-config')
require('feline-config')
require('indent-blankline-config')
require('treesitter-config')
require('lsp-config')
require('cmp-config')
require('nvim-ufo')
require('nvim-colorizer-config')
require('comment-nvim-config')
require('settings')

